name: Cultural Oil
favicon: null
layout_spectrum: 0.16130680916830897
typography_spectrum: 0.6100985002703965
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.2590783736668527
  lightness: 0.04148010886274278
  saturation: 0.9154697069898248
  rhythmicContrast: 0.32742132199928164
purpose: []
